project:
  type: website
  output-dir: _site

website:
  title: "Analyzing Data for Racial Equity"
  navbar:
    left:
      - text: "Home"
        href: index
      - text: "Module One: Identifying Injustice"
        href: modules/identifying-injustice
      - text: "Module Two: Interrogating Mechanism"
        href: modules/interrogating-mechanism

format:
  html:
    theme: litera
    toc: false
    self-contained: true
